### PR TITLE
Update patched GSM library

### PR DESCRIPTION
**Pull request by per1234**
The previous version of the patched GSM library doesn't work with Arduino IDE 1.6.3. I have updated the patched GSM library to version 1.0.3 included with Arduino IDE 1.6.4.
- This patch is untested because I don't own the GSM hardware but the examples do compile.
- Note for testing: Arduino IDE 1.6.4 locks up for me during compilation of any of the GSM library examples(unpatched or patched). This happens even with a fresh, unmodified IDE installation. Other sketches compile without problems. Arduino IDE 1.6.3 compiles all GSM library v1.0.3(patched and unpatched) examples without problems.

### CODE REVIEW

**Comment by pico--** [comment]
Pull request for "Update patched GSM library #13" merged.

**Comment by pico--** [comment]
A bit of a worry that 1.6.4 locks up! Sounds like a serious bug. BTW, do you have a handle on arduino.cc? (I'm "pico" there.)

**Comment by per1234** [comment]
Yes, I'm not sure what's going on with the lock up, but I've determined it's definitely not a Mighty 1284P problem. I'll have to look into it a bit more and then post an issue report to Arduino. I'm pert on arduino.cc, I don't do much on the forum but I try to put some work in on the Playground from time to time.

**Comment by pico--** [comment]
FWIW, I just downloaded 1.6.4 for 64-bit WIndows 7, and I was able to compile the GSM "SendSMS" example sketch without hanging for the mighty-1284p-v1.6.3 zip download. What environment are you using?

**Comment by per1234** [comment]
The same as you, and that one locks on me, so it must have something to do with my system.

**Comment by pico--** [comment]
I've just sent you a PM on arduino.cc with my email contact if you want to take any discussion off-line.

**Comment by pico--** [comment]
hi Per,

Did you post your issue report re 1.6.4 locking up? I've had an 
experience with 1.6.4 locking up on a particular sketch -- nothing to do 
with mighty-1284p. (It was for a Teensy 3.x, actually.) Everything 
worked as expected under 1.6.3 (and all other IDE versions I tested), so 
I suspect there' s a systemic problem in 1.6.4.

To give you an idea of how sensitive the lock-up condition is, I merely 
changed

```
 (for int i = 0; i < sizeof(array); i++)
```

to

```
 (for int i = 0; i < (int)sizeof(array); i++)
```

in order to get rid of a compiler warning regarding comparing signed and 
unsigned integer types. That single change was enough to get the 
compilation to complete! There were various other things I could change 
as well, either singly or in combination, to get the compilation to 
continue, but leaving the code in a particular state meant it would 
always lock-up under 1.6.4. Difficult to debug without diving into the 
IDE to catch precisely where the hang was occurring.

-Mark

**Comment by per1234** [comment]
Yes, I found an issue report someone had made on the issue and added my input. Arduino just fixed it earlier today. The fix is in the [hourly build](http://arduino.cc/download.php?f=/arduino-nightly-windows.zip). Using that build the modified GSM examples now compile for me so that verifies that that was not a problem with the patched library. The reason we got different results might have been different settings of **_File > Preferences > Compiler warnings**_.

**Pull request merged**
