### PR TITLE
Arduino IDE 1.5+ compatibility

### PR DESCRIPTION
**Pull request by per1234**
- Updates folder structure and boards.txt to be compatible with Arduino IDE 1.6.3. The previous structure is left intact to retain 1.0.x compatibility.
- The previous versions of the patched Ethernet and GSM libraries don't work with Arduino IDE 1.6.3 so I have added patched versions of the libraries included with 1.6.3. I have tested the GSM library because I don't have the GSM hardware but all examples compile.

I'm happy to make changes if you prefer it to be set up differently. Thanks, Per

### CODE REVIEW

**Comment by pico--** [comment]
hi Per,

Could you have a look at the thread I started regarding directory structure and file changes for 1.6.x at

http://forum.arduino.cc/index.php?topic=304961.0

and tell me if there are any differences in your conclusions? In particular, the 

tools/Mighty-1284p/avr 

directory structure, rather than a 

tools/avr 

directory structure?

Secondly, to keep the files change differences visible from the directory structure changes from 1.0.6, I would suggest at least two pull requests:

The first to set up the directory structure, but no file changes wrt 1.0.6 files.

Later ones to reflect the various files that have need to be changed since 1.0.6.

This is just to help keep track of what has been modified at the individual file level between the two versions.

I appreciate the Ethernet and GSM libs are starting from scratch with the new versions  distributed in 1.6.3; in that case, probably start by including the unmodified 1.6.3 files in the first pull request, then the updated versions with the patches that have been reapplied from the 1.0.6 patched versions.

-Mark

**Comment by per1234** [comment]
Hi Mark, Thanks for your input!
Did you mean to write hardware instead of tools for the directory structure? If so I think it is better to use hardware/mighty-1284p/avr because this keeps the mighty-1284p 1.0.x and the 1.6.x files together under the same folder instead of having to have hardware/mighty-1284p for 1.0.x and hardware/avr/mighty-1284p for the 1.6.x files.

The reason I think it is better to have one branch support both IDE versions instead of having a separate branch for each IDE version is that I am still using both IDE versions so I can test if code will work on either one. This also makes installation a bit more simple because users don't have to determine which branch they need.

The only real difference I see between what I have done and what you have proposed on the forum is that I have not created a platforms.txt and programmers.txt. I did go back and forth on adding a platform.txt with `name=Mighty 1284p Boards` but I decided that the extra entry in the Boards menu was not justified but I could go either way on that. There is no need for a new programmers.txt because mighty-1284p does not have any separate programmer requirements from whatever standard programmers.txt the user already has in their installation.

I did not create a separate commit for the creation of the new folder structure because I only modified boards.txt, all bootloader and variant files are just copied into the new folders. Some people are uptight about keeping the number of commits added by a pull request to a minimum but I think it's worth adding another commit to make it more clear what changes were made and am happy to do so. I don't think that multiple pull requests would be appropriate for this change because the commits are all integrally related to each other and this would just increase the workload on the repository maintainer to look at multiple pull requests. I did separate commits for the library patches because there the changes are a bit more difficult to track and it will be useful to easily see what files needed to be modified when new versions of the libraries need to be patched in the future.

**Comment by pico--** [comment]
Yes. I did mean "hardware" not "tools" - sorry. So yes, I was suggesting hardware/mighty-1284p/avr as the appropriate place in the directory tree.

I also don't have a strong opinion about platforms.txt and programmers.txt -- I thought the ability to customise and distinguish the parameters for the Mighty-1284p boards might potentially be an advantage, so I leant the other way.

I'm also not fussed if you want to do the second "file changes" commit all in one go; unlike some, perhaps, I prefer smaller more focussed commits that address a particular issue, rather than the "bucket" approach. So I'd probably do the official libs patches as a separate pull, for example, but that's just me. 

Sounds like we're on the same page here as far as the substantive stuff goes, which is the important thing -- perhaps we should wait for Jack and any others who may be interested to weigh in before we merge the requests. If we don't hear anything in a day or so I can approve the merge, as Jack has set me up for that.

-Mark

**Comment by per1234** [comment]
Ok, so just to verify, are we in agreement on the current folder structure as I have it in my pull request?

The problem I see with having a separate platform.txt for Mighty 1284P is that it will need to be updated whenever Arduino changes the format which has happened a couple times already recently. Also it will override the user's configuration of the standard platform.txt(for example I have -Wall compiler flag and I would have to add this to the Mighty 1284P platform.txt also). It seems like unless we need specific changes from the standard platform.txt for Mighty 1284P to work(which I haven't found to be the case) then it is better to just let the user create their own platforms.txt if they need it. The exception to this is if you want the Boards menu section to have a title then I would recommend making a platform.txt that only contains the `name=Mighty 1284p Boards` and nothing else. This way all other settings will still be taken from the standard platform.txt.

As for programmers.txt I don't see any need for changes from whatever configuration the user already has in their other programmers.txt files so unless there are separate configurations needed for Mighty 1284P(which I haven't found to be the case) then I think it is best not to have that file. I suppose that there could be a blank programmers.txt file but I don't really see the purpose for that.

I hadn't realized you were one of the project collaborators so I am happy to do multiple pull requests. I thought you meant to do one PR for the new folder structure creation, then another for the boards.txt modification. It makes sense to do one PR for the new folder structure creation(one commit) and boards.txt modification(one commit), then another PR for the add unpatched libraries(one commit) and patch the libraries(one commit). Or if you want me to do a separate pull request for each library I can do that also and you can decide if you want the untested patched GSM library to be added. My feeling is that it will probably work as the changes are pretty much the same as the previous patch and at any rate it is a good start towards having a working GSM library for 1.6.3 rather than nothing at all, but I would rather have been able to test it before making the PR.

I'll wait a couple days to make any changes to my pull request to see if there is any other input. Thanks!

**Comment by pico--** [comment]
I'd personally like to see the 1.0.6 and 1.6.x trees downloadable as separate install zip files, rather than combining the 1.0.6 stuff and 1.6.x stuff in one combined directory. If I understand your proposed pull, you are adding an avr directory under Mighty-1284p, and putting all the 1.6.x files under that, while also having the 1.0.6 files directly under under Mighty-1284p. 

If so, I think that could be potentially confusing. Is this indeed what you are proposing?

**Comment by per1234** [comment]
Yes, that is my proposal, to have one installation that supports both IDE versions. The reason I think it is better to have one branch support both IDE versions instead of having a separate branch for each IDE version is that I think many people are currently using both versions simultaneously(for example I use both IDE versions so I can test if code will work on both), others may be working with some old sketches or libraries that don't work with 1.5+. So if there were 2 separate branches then I would have to install both branches. This also makes installation a bit more simple because users don't have to determine which branch they need. I don't really see it as being more confusing this way but I am willing to create a 1.6.x only version instead if you want to have two branches.

**Comment by pico--** [comment]
The reason I think it could be potentially confusing is that for anyone who is trying to understand how these files work and are interpreted by the version of IDE they have installed, there would be redundant/duplicated files in the two overlapping directory trees, half of which are relevant, the others not at all. Given that the design of the IDE trees is hardly transparent or particularly rational in the first place, this makes it all that much more difficult to figure out what' is actually doing what.

I also use the both 1.0.6 and 1.6.x, but I have the Mighty-1284p files installed separately under the install directory of each IDE, rather than under my general "sketches" directory. So, under  

 \Arduino 1.0.6\hardware\Mighty-1284p

I have the 1.0.6 files, and under

 \Arduino 1.6.3\hardware\Mighty-1284p\avr

I have the 1.6.x files. 

Personally, I prefer to tie the files to each IDE in this way, rather than to have any ambiguity of what IDE is accessing what files in the tree -- just seems much "cleaner" that way.

 And to tell you the truth, I'm not even 100% confident that future versions of the IDE won't itself get confused, with unpredictable results! (But perhaps that just reflects my prejudices...)

Finally, if a user wants to download and overlay both trees manually, it's not hard to do. Harder to unscramble the egg, rather than scramble it in the first place!

**Comment by per1234** [comment]
I am ready to make the requested changes to this pull request. I believe you have to create the new branch for me and then I will make a new pull request because there is no way to change the base branch of this one.

**Comment by pico--** [comment]
OK, I'll have to have to read up on how to create a new branch. It would be preferable if Jack could weigh in on how he'd prefer to do this, but he doesn't seem to be in the loop right now.

**Comment by pico--** [comment]
hi Per,

I have created a v1.6.3 branch loaded with an initial version of the updated files for 1.6.3   -- have only updated README.md and boards.txt at this stage. I haven't made any of the changes you flagged for the official libs.

See how you go cloning this branch and making any additional changes. When you have generated a pull request I will see if I can merge the changes into the new v1.6.3 branch. Thanks for your patience!

**Comment by per1234** [comment]
Thanks! I have made the first pull request. 

Next will be the updated patched libraries but I'm not sure if mighty-1284p/avr/patched-libs is the best place for the patched libraries. It seems like it would make more sense to keep the patched library folder at mighty-1284p/patched-libs. What do you think?

I noticed that you had changed the low_fuses to 0xf7 in 3ba13c9  and then back to 0xff later, have you also had problems using the ATmega1284P with the 0xff setting? I have intermittent problems uploading large sketches to my homemade board unless I change it to 0xf7. Even with small sketches the 1Mbps board entry only works for me this way.

**Comment by pico--** [comment]
Placing the patched-libs folder directly under hardware/mighty-1284p would cause a problem if a user wanted to install both the 1.0.x and 1.6.x trees over each other, as you were suggesting some people would prefer in our earlier discussion. 

However, I was thinking that moving all the patched libraries under mighty-1284p/avr/libraries might be a good change, because that would automatically make them the default libraries when using mighty-1284p under 1.6.x, meaning the user doesn't have to do an additional installation of manually installing the libraries. 

What do you think?

As for the low fuse setting, you re right, it should be  0xf7, not 0xff -- I'm not sure how or when that crept back in. But good thing you spotted it!

**Comment by pico--** [comment]
I've now merged your new pull request, so I'm going to close this pull request.

**Comment by per1234** [comment]
> patched-libs folder directly under hardware/mighty-1284p would cause a problem if a user wanted to install both the 1.0.x and 1.6.x trees over each other

Yes you're right, that makes perfect sense.

> mighty-1284p/avr/libraries might be a good change, because that would automatically make them the default libraries when using mighty-1284p under 1.6.x

I think that's a great idea. It doesn't seem to work with the libraries under **mighty-1284p/avr/libraries/official** and **mighty-1284p/avr/libraries/unofficial** so all the libraries would have to be put directly under **mighty-1284p/avr/libraries** but I don't see a problem with that.

> As for the low fuse setting, you re right, it should be 0xf7, not 0xff -- I'm not sure how or when that crept back in.

The low fuse has always been 0xff since the maniacbug days. This is the low power crystal oscillator setting and is what the official Arduino boards use also. I'm sure it works fine with a well designed pcb but with my stripboard ATmega1284P board I need to use the full swing setting(0xf7). I was wondering if there would be interest in adding a Tools>Clock menu with low power, full swing and internal 8Mhz options. It seems like a lot of people experimenting with ATmega1284P may be using them on breadboards where the more forgiving full swing could be useful.

**Comment by pico--** [comment]
OK, lets put the libs directly under mighty-1284p/avr/libraries then.

The other thing that is worth considering is dropping support for the patched SdFat lib, as the latest SdFat beta has direct support for mighty-1284p now. That means we would only have to put the patched official libs under libraries.

Or the compromise might be to have a folder for any unofficial patched libs (maybe avr/patched-3rd-party-libs), so we have a place for these but they will require manual installation. That way we could keep support for the patched SdFat lib, at least until the latest beta is released as the latest stable version.

What do you think?

**Comment by pico--** [comment]
The curious thing about the low fuse setting is that I believe we had changed this to 0xf7 the original 1.0.5 release -- I'll have to go and check now. In any case, now that you've alerted me to the problem, I'll check 1.0.5 and 1.0.6 as well.

**Comment by per1234** [comment]
> have a folder for any unofficial patched libs (maybe avr/patched-3rd-party-libs), so we have a place for these but they will require manual installation

I'd say keep the SdFat library in the avr/patched-3rd-party-libs and remove it when the new version is stable.

**Comment by pico--** [comment]
OK, let's do it with the official libs under avr/libraries, and patched SdFat under avr/patched-3rd-party-libs.

I've just corrected the 0xff to 0f7 low fuse issue for 1.6.3. Have to go back and make the changes in 1.0.5 and 1.0.6 now...

**Pull request closed without merging**
